### ISSUE TITLE
Dutch translation issues

### ISSUE THREAD

**Issue by DcR-NL** [razzeee/script.trakt#201]
Line 125 (translation for "What Did You Think?") isn't correct because _vondt_ isn't a real word (bad spelling),  but _vond_ is right. "Wat _vondt_ je er van?" should be "Wat _vond_ je er van?".

Also, the translation for "Meh" is currently "Bah". _Bah_ is something you would say about food if it tastes bad (as in when it tastes _bad_/_dirty_), it would be better if this was used as translation for "Bad". But as it is now I would like to recommend changing the translation for "Meh" (line 149) to "Mwa". _Mwa_ isn't a word you would find in the dictionary but it is as accepted as "Meh" is, and means exactly the same as "Meh".

@Razzeee can you (or somebody else) confirm and/or change this?  If not, I'm going to create a pull when I find the time. :)

**Comment by s7eele** [comment]
pull request 158 for razzeee/script.trakt  applies:

https://github.com/Razzeee/script.trakt/pull/158

it is about dutch translation but im not sure if it addresses the same exact thing your issue is about, you should check yourself probably but the outcome was that the creator of the pr was going to update the

**Comment by razzeee** [comment]
This should also be done at transifex
https://github.com/trakt/script.trakt#translations
