### ISSUE TITLE
No longer focused on rating slider

### ISSUE THREAD

**Issue by tevi** [razzeee/script.trakt#210]
When I installed the beta version the rating dialog no longer focused on the slider. This required the use of the mouse to select a rating instead of just the keyboard.

I don't know enough about kodi's addon engine to debug or provide more details than my description.

**Comment by razzeee** [comment]
Well i've seen this yesterday when developing but thought its a random quirk of the version not beeing installed properly. 
Havent touched the focus part at all :/

**Comment by s7eele** [comment]
hey @Razzeee, not sure it matters but i wanted to mention that i am seeing the same focus issue with latest -dev on 14.2 on android, definitely no urgency or need to respond just providing input, not a real bother and i use it with the understanding it is -dev and everything that entails, just fyi

**Comment by razzeee** [comment]
@tknorris can you have a look? I really have no idea why this would happen :/

**Comment by tknorris** [comment]
That's strange. I'm using the beta on my main htpc and I'm not having a focus issue. Is everyone having this problem running Confluence?

**Comment by razzeee** [comment]
It's not in the beta yet, its in the dev branch on my repo

**Comment by tknorris** [comment]
tevi said he had the beta installed...

**Comment by tknorris** [comment]
If it's in the dev branch, but not the beta, then it would have to be this commit: https://github.com/Razzeee/script.trakt/commit/c6e907a172cd47d365116238a8cd7127451c55c4

though, I can't see possibly what in that commit could cause it. When a dialog pops up it automatically gets focus. So, the only thing I could think would be missing onXX elements in the dialog.xml but they are clearly there.

I will also say that I know for sure the beta currently works on my system because I watched two movies last night that I rated using my remote.

**Comment by razzeee** [comment]
Yeah, I know which commit is causing it, but the setFocus that was always there shouldn't be affected by that

**Comment by tknorris** [comment]
Hmm. I just confirmed the bug with my dev machine running your latest dev branch..weird

**Comment by tknorris** [comment]
here's the problem. not sure why it's happening yet though.
11:52:54 T:2837441344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: int() argument must be a string or a number, not 'dict'
                                            Traceback (most recent call last):
                                              File "/home/tknorris/.kodi/addons/script.trakt/rating.py", line 190, in onInit
                                                if self.rerate and self.media['user']['ratings'] and int(self.media['user']['ratings']['rating']) > 0:
                                            TypeError: int() argument must be a string or a number, not 'dict'
                                            -->End of Python script error report<--

**Comment by tknorris** [comment]
ahh, it's this change here: https://github.com/Razzeee/script.trakt/commit/c6e907a172cd47d365116238a8cd7127451c55c4#diff-a534c3c8963e6e7695f1d2cd016b98c7R156

You changed the retrieved ratings from the actual rating value to a dict. I'm not sure what your intent behind that change was though?

**Comment by razzeee** [comment]
Well I thought it is the same dict as for e.g. this one? https://github.com/Razzeee/script.trakt/commit/c6e907a172cd47d365116238a8cd7127451c55c4#diff-6ac7ee278f767d4bea0fa5eb9f3a189eR63
So I thought the path was wrong and it couldn't have worked before

**Comment by tknorris** [comment]
It is the same dict, but "rating" is a key in the ratings dict. It looks like this:

12:02:16 T:2835344192   DEBUG: [script.trakt] rating: Summary Info {'plays': 0, 'title': u'Interstellar', 'last_watched_at': None, 'collected_at': None, 'ids': {'tmdb': '157336', 'imdb': 'tt0816692', 'slug': 'interstellar-2014', 'trakt': '102156'}, 'watched': 0, 'user': {'ratings': {'rating': 10, 'plays': 0, 'title': u'Interstellar', 'last_watched_at': None, 'collected_at': None, 'ids': {'tmdb': '157336', 'imdb': 'tt0816692', 'slug': 'interstellar-2014', 'trakt': '102156'}, 'rated_at': '2015-02-25T23:20:06.000-00:00', 'watched': 0, 'year': 2014, 'collected': 0, 'progress': None, 'paused_at': None}}, 'year': 2014, 'collected': 0, 'progress': None, 'paused_at': None

I changed it back to the way it was before and everything works again. I didn't test the multi-part episode thing though because I don't have any of those.

**Comment by razzeee** [comment]
Can you pr this? As I'm on the road

**Comment by tknorris** [comment]
sure

**Comment by razzeee** [comment]
Thanks!

**Comment by tknorris** [comment]
PR sent.

**Comment by razzeee** [comment]
Hasn't fixed it for me. Still happening, even with movies.

**Comment by tknorris** [comment]
Did you restart xbmc? I'm positive it fixed it for me.

**Comment by razzeee** [comment]
log seems like you missed a spot :/
I try to have a look later

**Comment by tknorris** [comment]
It could be because I only tested manual rating a nonlibrary item. It might need a fix for library items as well. I'm walking out the door though. I'll look later as well.

**Comment by razzeee** [comment]
Well my last two commits should have fixed everything
Thank you so much @tknorris
