### ISSUE TITLE
New collected movies in Kodi get rating of 1

### ISSUE THREAD

**Issue by blazer380** [razzeee/script.trakt#274]
This issue seems to have started after I've upgraded Kodi to the latest version (16/Jarvis) on Windows 10 PC. Every new movie that is added to my collection, gets a rating of 1 on trakt. The movies are not watched or rated by me. Past unwatched movies are not affected and stay unrated, but any new movie automatically gets a rating of 1 as soon as it's added to my collection. Also if I login to my trakt account online and unrate the 1 rated moves, next time Kodi scrobbles, it rates them 1 again.

![screen shot 2016-03-03 at 9 41 22 am](https://cloud.githubusercontent.com/assets/3440127/13501611/f947bca8-e12c-11e5-9893-f018e1229bbd.png)

**Comment by thwaller** [comment]
I have this same issue, except I would narrow it down to starting with Trakt addon version 3.1.0. What I experience is the same as described above. I can manually take care of this by removing the rating on Trakt.tv and manually editing the Kodi database to reflect not rated (null value). On a re-sync, it usually corrects this. Exceptions are other _bugs_ such as a missing or wrong tt number from IMDB in the mix. I will attempt to gather my notes on that one and post it separately.

Reverting the addon back to 3.0.7 eliminates this issue as described here. It also fixes the not asking for a rating after watching a tv show or movie from an addon. This issue is reported by another user separate from this.

**Comment by thwaller** [comment]
@blazer380- I was able to correct your issue of reverting back to a 1 rating by manually editing the userrating field in the local Kodi database. I just open the table and clear the value (which is 1). This places it at null. This _fix_ only works if there are no other data anomalies, such as a missing or incorrect tt from IMDB. Get that corrected if that is the case, wait 24+ hours and try this again. The 24 hours is to get changes on TVDB and/or TMDB replicated to the Trakt databases.

**Comment by blazer380** [comment]
@brianzech - Thanks for the suggestion, but that seems to be just a quick-fix and I will have to do that for every new movie added. I'm also on version 3.1.0 but that is the version that's supposed to work with Kodi 16 so reverting back to 3.0.7 might not be possible.

**Comment by thwaller** [comment]
Yes, it is a quick fix only. I have to do this for every new movie added as well. I am also using the latest v16 of Kodi and the older release of 3.0.7 works perfectly. For me, the changes in 3.1.x are not needed or wanted, so I am good with it until the issues with the 3.1.x version are resolved. I am running this on Win10 and Ubuntu 14.04.

**Comment by razzeee** [comment]
Hopefully fixed by https://github.com/trakt/script.trakt/commit/5316498f5e5b89b6557a0dd56598ebd74e557e7a

**Comment by thwaller** [comment]
Will grab it and give it a go!

**Comment by blazer380** [comment]
Installed the latest 3.1.3. It seemed to have fixed the issue but I had to manually edit the kodi database to clear some of the 1 ratings as @brianzech suggested above as well as clearing the 1 ratings on trakt.tv website. Now that works as intended, BUT I found another glitch with authentication. Will open a separate ticket for that.
