### ISSUE TITLE
Trakt in Kodi asks to authenticate each time Kodi starts

### ISSUE THREAD

**Issue by blazer380** [razzeee/script.trakt#278]
Just updated to 3.1.3 of Trakt and now if I exit Kodi and open it again, Trakt won't sync unless I go through the authentication process each time. trakt.tv\pin### process. The authentication seems to only work for that session.

Kodi 16 on Windows 10 PC.

**Comment by thwaller** [comment]
I am not experiencing this issue. I used the zip file from this site to do the update to 3.1.3. I am on Kodi 16 on Ubuntu 14.04.

**Comment by blazer380** [comment]
Ok, this is a little odd. If I just open Kodi and go to Programs > Trakt, it doesn't do anything. If I open Kodi, open MOVIES, then go back and into Programs > Trakt, then it works. So weird. I'm using the latest version of the Mimic skin if that matters.

**Comment by thwaller** [comment]
I experience something similar to that. For me, once I open Kodi, executing the addon does not work for approx 2 minutes. After that, it works on Run. According to the log, it shows the clicks and states that it is already running. Given this, I assume that when I try and run it right away, it is already running on startup. After this completes, then I can run it again, manually.

Maybe your issue is the same? The wait from the first run attempt to the navigation to the second may be giving it enough time to complete its initial run? If you see otherwise, let me know, this is something I was looking at too.

**Comment by blazer380** [comment]
@thwaller You are correct. I had to wait 60 seconds for it to work. I guess this is a non-issue :)
