### ISSUE TITLE
Traceback:  ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by fernandog** [razzeee/script.trakt#395]
@Razzeee From logs:

```
10:55:44.099 T:1458566128   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.trakt/defaultscript.py", line 14, in <module>
                                                Main()
                                              File "/home/osmc/.kodi/addons/script.trakt/defaultscript.py", line 11, in Main
                                                script.run()
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/script.py", line 91, in run
                                                data['dbid'] = int(xbmc.getInfoLabel('ListItem.DBID'))
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
```

**Comment by razzeee** [comment]
Which kodi version/build? Can you try with anything non osmc?

**Comment by fernandog** [comment]
@Razzeee thanks fror replying. I have only osmc to test it.
 I'm also a python developer and I can assure is not a osmc related issue

I can check my kodi database for any empty DBID If I knew which table/column to look at

imho It is a issue related to a show wrong data...

so why don't you do this as you can't control show data?
```python
data['dbid'] = int(xbmc.getInfoLabel('ListItem.DBID')) if xbmc.getInfoLabel('ListItem.DBID') else ''
```

But again, i don't know if having a `data['dbid'] = ''` may cause other issues

```
10:35:49.608 T:1958395904  NOTICE: Starting Kodi (17.3). Platform: Linux ARM (Thumb) 32-bit
10:35:49.608 T:1958395904  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
10:35:49.608 T:1958395904  NOTICE: Kodi compiled Jul 29 2017 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.39 (200743)
10:35:49.608 T:1958395904  NOTICE: Running on Open Source Media Center 2017.07-1, kernel: Linux ARM 32-bit version 4.9.29-9-osmc
```

**Comment by razzeee** [comment]
Well it shouldn't be possible to have an empty `ListItem.DBID` as it's the id of the currently selected listitem. And it's in the twig that's handling rates and unrates, so you try to rate with nothing selected? Makes it sound like a core problem.

**Comment by fernandog** [comment]
I have button mapped that calls `RunScript(script.trakt,action=contextmenu)`

So I might explain If I clicked the button without selecting anything. It's possible
The traceback breaks the service right?
If yes, can you check if `ListItem.DBID` is available and if not available gives a notification or just return and do nothing?

**Comment by razzeee** [comment]
Sure, that's why an explanation how you provoked that error is always helpful.

**Comment by alphaleonis** [comment]
I have the same error when using the context-menu from Aeon MQ to invoke a trakt item, such as "Rate this show" or "Toggle watched".  The items should originate from context.trakt.contextmenu I'm guessting. Not sure if the bug is in script.trakt or context.trakt.contextmenu, or perhaps in Aeon MQ?

**Comment by razzeee** [comment]
Hard to tell without a complete logfile

**Comment by alphaleonis** [comment]
Not sure if this log file is of much help, but attaching it anyway. What I did was basically just to launch Kodi, naviagte to a TV-show episode, open the context menu of this episode, and then select "Trakt" followed by "Toggle Watched", which led to this error.

[kodi.zip](https://github.com/trakt/script.trakt/files/1609892/kodi.zip)

**Comment by razzeee** [comment]
Are you able to print `xbmc.getInfoLabel('ListItem.DBID')` in the source code?
Seems like the `ListItem.DBID` is not an integer for you, which scrapers are you using?

**Comment by alphaleonis** [comment]
It appears that both ListItem.DBID and ListItem.DBTYPE are empty in this case.  I also tried switching skins to Confluence, and in that skin it works without a hitch. So I'm guessing it must be a problem with what the Aeon MQ 7 Krypton skin does then. :(

**Comment by benkap** [comment]
I confirm same issue with AEON MQ 7 Skin... Any ideas?

**Comment by razzeee** [comment]
You should talk with the skin author about this.

**Comment by benkap** [comment]
I had some free time to look into it - specifically what is the difference between the skins that make 

`
xbmc.getInfoLabel('ListItem.DBID')
`

return nothing/empty. 

In AeonMQ if you don't install the added context menu for 'rated' and 'watched' there is a sub-menu called 'trakt' (I'm sure you know :) ) where you basically have the same functionality as the 'context addons:

AeonMQ:

-  Trakt (from main context menu) opens ->
1. Add To Watchlist
2. Rate This Movie
3. Toggle Watched
4. Synchronize Library 

Now i can confirm that when using the two buttons from the 'context addons' all is working as expected even on AeonMQ. So when using buttons from the main kodi context menu all is working.
But if you use the 'Trakt' item which open a sub-menu all actions that depended on the selected item fail (since ListItem is empty) while the 'Synchronize Library' works fine.

I am not a developer and barely knows the kodi addons platform but couldn't this be that when going to the sub-menu xbmc.getInfoLabel('ListItem.DBID') cannot return the item ID since the item that is now selected is not the Media (Movie) but the 'Trakt' main context menu? can that be right? 

And if this is correct, while i am not saying that you should support all skins out there i think that this is not that of a rare or strange case - To use a sub-menu from the main context menu and maybe that will be a great added feature that will support many other skins as well as the default one.

what do you think?

**Comment by razzeee** [comment]
Thank you for investigating this. But it sounds like a problem of kodi itself, as it seems like it does not provide a valid response for `ListItem.DBID`
